### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by virajsoni06** [okonet/metalsmith-remote-json-to-files#1]
Hey okonet,

I'm fairly new to Metalsmith(Or static site generators in general) . For one of my project I need to fetch data from an API. 

Everything that I need is available in Metalsmith, except fetching data from a API. I'd like to know how to use this plugin? And also when making a build will it download content and hard code in build files?

Thanks

**Comment by okonet** [comment]
I'll add a few examples for this plugin soon. Hopefully, this will help.

And yes, you can fetch any content and create new static pages using it or its metadata. This is how http://colorsnapper.com/changelog/ is built for example. Each version is a "release" from a GitHub project.

**Comment by okonet** [comment]
I've added a documentation and an example to the README. Please check it out and let me know if this is helpful enough. Thanks!

**Comment by virajsoni06** [comment]
Thanks okonet
