### ISSUE TITLE
Callback example

### ISSUE THREAD

**Issue by virajsoni06** [okonet/metalsmith-remote-json-to-files#2]
Hi okonet,

Thanks for adding a example. However, the example is a simplified via configuration object. Which is not really useful in a real word scenario.

I'd like to know two things - 
1. How does the callback function works? Could you please provide an example?
2. Currently it directly generates the static files. Is there a way to define a template to use?

Thanks,
Viraj

**Comment by okonet** [comment]
Also, you can see tests for some examples.

**Comment by okonet** [comment]
> Is there a way to define a template to use?

You can use other plugins with it, so it's up to you how you transform your files object. In the example, I use `collections` and `markdown` to generate http://colorsnapper.com/changelog/ page.
